import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";
const sidebars: SidebarsConfig = {
  vinayakSidebar: [
    {
      type: "category",
      label: "Vinayak Temples",
      items: [
        "about-vinayak",
        "dhundhi-vinayak",
        "abhay-vinayak",
        "ark-vinayak",
        "asha-vinayak",
        "avi-mukta-vinayak",
        "bhimchandi-vinayak",
        "chatur-dant-vinayak",
        "chintamani-vinayak",
        "chitra-ghanta-vinayak",
        "dant-hast-vinayak",
        "dehli-vinayak",
        "durg-vinayak",
        "durmukh-vinayak",
        "dwar-vinayak",
        "dwi-mukh-vinayak",
        "eka-danta-vinayak",
        "gaja-karna-vinayak",
        "gaja-vinayak",
        "gana-nath-vinayak",
        "gyan-vinayak",
        "heramba-vinayak",
        "jyeshta-vinayak",
        "kaal-vinayak",
        "kali-priya-vinayak",
        "kharva-vinayak",
        "koonitaksh-vinayak",
        "kooshmanda-vinayak",
        "koot-dant-vinayak",
        "kshipra-prasad-vinayak",
        "lambodara-vinayak",
        "mangal-vinayak",
        "manikarnika-vinayak",
        "mitra-vinayak",
        "moda-vinayak",
        "modak-priya-vinayak",
        "munda-vinayak",
        "nagesh-vinayak",
        "paas-pani-vinayak",
        "panchasya-vinayak",
        "pichandil-vinayak",
        "pramoda-vinayak",
        "pranav-vinayak",
        "raj-putra-vinayak",
        "shal-kant-vinayak",
        "shrishti-vinayak",
        "siddhi-vinayak",
        "singh-tund-vinayak",
        "sthool-dant-vinayak",
        "sumukh-vinayak",
        "tri-mukh-vinayak",
        "uddand-mund-vinayak",
        "uddand-vinayak",
        "vakra-tund-vinayak",
        "varad-vinayak",
        "vighna-raja-vinayak",
        "vikata-dwija-vinayak",
        "yaksh-vinayak",
      ],
    },
  ],
};

module.exports = sidebars;